# This is a basic workflow to help you get started with Actions

name: Update repo.json

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.2.0

      - name: Run the update script
        run: node scripts/update.js
        
      - name: Commit report
        run: |
          git config --global user.name 'A. Robot'
          git config --global user.email 'me+swmthemesautomated@thelmgn.com'
          git commit -am "Update repository"
          git push
